### ISSUE TITLE
Add support for upgrading forge version

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-tools#6]

**Comment by SwadicalRag** [comment]
Unless you wanted a `ts-node upgrade-mods-md.ts [old.md] [version number] > [new.md]`

**Comment by SwadicalRag** [comment]
which should be trivial to do anyway. Right now you can upgrade versions by just adding an extra column onto an existing md doc

**Comment by SwadicalRag** [comment]
https://gist.github.com/SwadicalRag/2c35dab78d093c2fd2473e32d780806b

here's what 1.14.4 w/ our old modpack looks like

**Comment by notcake** [comment]
Sorry swad this issue was about the install process. If you run the imaging command with a different forge version to what is installed it doesn't reinstall your newly specific version of forge.

**Comment by SwadicalRag** [comment]
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

nice
